
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/user_service_db?useSSL=false&serverTimezone=Asia/Ho_Chi_Minh
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: none
        dialect: org.hibernate.dialect.MySQL8Dialect

logging:
  level:
    root: info
    org.springframework: warn
    org.hibernate: error
    com.pos: debug
  pattern:
    console: "%d{HH:mm:ss} %-5level [%logger{36}] - %msg%n"


jwt:
  secret: "VExzN0s2V3p5R2Q1eXJzM29IVG95MFRhUG5nMUFzV1pCenFhWkYxclR0T29rUjJvT3pYckQ0UHVtN09uSjlSNEQxQ0FpY1BicHlCbmJsdmE1c293M01LQXlKMGZ5MXU="

server:
  port: 8081
  application:
    name: AuthenticationService